#开发环境
server:
  port: 3008

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Lapudamydream200!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

wx:
  appid: wx0dc4063b0624495e
  appsercret: 35b4bb409585b46684c68492e1fcbcf7
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  MchID: abc
  MchKey: def
  pay-callback-host: http://tianlb.cn
  pay-callback-path: /v1/payment/wx/notify

myTest:
    security:
        jwt-key: tyrealAnubrekhan
        token-expired-in: 86400000
        # 令牌的过期时间
    order:
        max-sku-limit: 888
        pay-time-limit: 3600
        # 订单支付的延迟控制
        year-codes: A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
        year-start: 2020
        #从year-start年开始每一年是一个字母
