#开发环境
server:
  port: 3009
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Lapudamydream200!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true



